import Link from "next/link";
import { DocsShell } from "./components/DocsShell";

const domains = [
  { title:"Architecture", href:"/architecture", label:"SYSTEM", copy:"Core, Mind, product boundaries, learner/educator models, capability ownership, trust, and cross-product contracts.", accent:"from-[var(--lx-primary)] to-[var(--lx-secondary)]", count:"Architecture decisions" },
  { title:"Product", href:"/product", label:"PRODUCT", copy:"Authoritative product responsibilities, experience boundaries, MVP definitions, roadmap-facing product decisions, and ecosystem rules.", accent:"from-[var(--lx-secondary)] to-[var(--lx-accent)]", count:"Product source of truth" },
  { title:"Curriculum", href:"/curriculum", label:"LEARNING", copy:"Lurexa methodology, CEFR progression, competency models, assessment, phonetics, conversation, and activity standards.", accent:"from-[var(--lx-accent)] to-[var(--lx-success)]", count:"Pedagogical authority" },
  { title:"Engineering", href:"/engineering", label:"BUILD", copy:"Repository conventions, platform implementation, environments, deployment, verification, APIs, and engineering operations.", accent:"from-[var(--lx-secondary)] to-[var(--lx-primary)]", count:"Implementation guidance" },
  { title:"Governance", href:"/governance", label:"TRUST", copy:"Decision authority, documentation governance, repository standards, AI-agent constraints, and change discipline.", accent:"from-[var(--lx-primary)] to-[var(--lx-primary)]", count:"Decision controls" },
  { title:"Design", href:"/design", label:"EXPERIENCE", copy:"Brand system, visual language, product identity, interaction patterns, accessibility, and shared experience principles.", accent:"from-[var(--lx-destructive)] to-[var(--lx-primary)]", count:"Experience standards" },
];

const principles = [
  ["01","Core owns trust","Identity, authorization, authoritative persistence, evidence provenance, and safe cross-product contracts."],
  ["02","Mind interprets learning","Personalization and recommendations operate on authorized evidence without becoming the source of truth."],
  ["03","Products own experiences","Learn, Coach, Teach, Admin, Insight, and Studio remain distinct while sharing trusted ecosystem capabilities."],
];

export default function DocumentationHome() {
  return <DocsShell><main>
    <section className="relative overflow-hidden border-b border-[var(--lx-border)] bg-white">
      <div className="absolute -left-28 top-20 h-80 w-80 rounded-full bg-[var(--lx-primary)]/10 blur-3xl"/><div className="absolute -right-28 top-0 h-96 w-96 rounded-full bg-[var(--lx-accent)]/10 blur-3xl"/>
      <div className="relative mx-auto grid max-w-[1480px] gap-12 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1.15fr_.85fr] lg:items-center">
        <div><div className="inline-flex min-h-9 items-center rounded-full border border-[var(--lx-border)] bg-[var(--lx-surface)] px-3 text-[10px] font-extrabold uppercase tracking-[.18em] text-[var(--lx-primary)]">Authoritative ecosystem documentation</div><h1 className="mt-6 max-w-5xl text-5xl font-black leading-[.94] tracking-[-.07em] sm:text-7xl lg:text-[78px]">Understand Lurexa.<br/><span className="bg-gradient-to-r from-[var(--lx-primary)] via-[var(--lx-secondary)] to-[var(--lx-accent)] bg-clip-text text-transparent">Build it coherently.</span></h1><p className="mt-7 max-w-2xl text-base leading-8 text-[var(--lx-muted)] sm:text-lg">Architecture, product rules, curriculum methodology, engineering guidance, governance, and design standards—organized as one operating knowledge system for the Lurexa ecosystem.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/architecture" className="inline-flex min-h-12 items-center rounded-xl bg-gradient-to-br from-[var(--lx-primary)] to-[var(--lx-secondary)] px-5 text-sm font-extrabold text-white shadow-[0_14px_30px_rgba(71,65,190,.22)]">Start with architecture →</Link><Link href="/product" className="inline-flex min-h-12 items-center rounded-xl border border-[var(--lx-border)] bg-white px-5 text-sm font-extrabold text-[var(--lx-secondary)]">Explore product rules</Link></div></div>
        <aside className="rounded-[30px] border border-[var(--lx-surface)] bg-[var(--lx-canvas)] p-6 shadow-[0_18px_50px_rgba(32,52,128,.08)] sm:p-8"><p className="text-[10px] font-extrabold tracking-[.18em] text-[var(--lx-primary)]">SOURCE-OF-TRUTH ORDER</p><div className="mt-5 space-y-3">{[["1","Current product-owner decision"],["2","Lurexa Bible"],["3","Architecture / curriculum specifications"],["4","Roadmap and implementation contracts"],["5","AI-agent helper context"]].map(([n,label])=><div key={n} className="flex items-center gap-4 rounded-2xl border border-[var(--lx-border)] bg-white p-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[var(--lx-surface)] text-sm font-black text-[var(--lx-primary)]">{n}</span><b className="text-sm">{label}</b></div>)}</div><p className="mt-5 text-xs leading-5 text-[var(--lx-muted)]">Newer explicit decisions supersede stale assumptions. Documentation should clarify conflicts rather than blending incompatible models.</p></aside>
      </div>
    </section>

    <section className="mx-auto max-w-[1480px] px-5 py-14 sm:px-8 sm:py-18"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[var(--lx-primary)]">DOCUMENTATION DOMAINS</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em] sm:text-4xl">Navigate by responsibility, not file hunting.</h2></div><p className="max-w-xl text-sm leading-6 text-[var(--lx-muted)]">The portal mirrors the repository’s documentation domains so the website and source tree stay conceptually aligned.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{domains.map((domain)=><Link key={domain.title} href={domain.href} className="group flex min-h-[260px] flex-col rounded-[26px] border border-[var(--lx-surface)] bg-white p-6 shadow-[0_12px_30px_rgba(32,52,128,.055)] transition hover:-translate-y-1 hover:border-[var(--lx-border)] hover:shadow-[0_20px_42px_rgba(32,52,128,.10)]"><div className={`h-2 w-16 rounded-full bg-gradient-to-r ${domain.accent}`}/><p className="mt-6 text-[10px] font-extrabold tracking-[.16em] text-[var(--lx-muted)]">{domain.label}</p><h3 className="mt-2 text-2xl font-black tracking-[-.045em]">{domain.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--lx-muted)]">{domain.copy}</p><div className="mt-auto flex items-end justify-between pt-6"><span className="text-xs font-bold text-[var(--lx-muted)]">{domain.count}</span><span className="grid h-11 w-11 place-items-center rounded-full bg-[var(--lx-surface)] font-black text-[var(--lx-primary)] transition group-hover:translate-x-1">→</span></div></Link>)}</div></section>

    <section className="border-y border-[var(--lx-border)] bg-[var(--color-brand-navy)] text-white"><div className="mx-auto max-w-[1480px] px-5 py-14 sm:px-8 sm:py-16"><div className="grid gap-8 lg:grid-cols-[.65fr_1.35fr] lg:items-start"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[var(--lx-accent)]">THE LUREXA MODEL</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em] sm:text-4xl">One ecosystem.<br/>Clear ownership.</h2><p className="mt-4 max-w-md text-sm leading-7 text-indigo-100">Documentation should make responsibility obvious before implementation starts.</p></div><div className="grid gap-3 md:grid-cols-3">{principles.map(([n,title,copy])=><article key={n} className="rounded-[24px] border border-white/12 bg-white/8 p-6"><span className="text-xs font-black text-[var(--lx-accent)]">{n}</span><h3 className="mt-5 text-xl font-black">{title}</h3><p className="mt-3 text-sm leading-6 text-indigo-100">{copy}</p></article>)}</div></div></div></section>

    <section className="mx-auto max-w-[1480px] px-5 py-14 sm:px-8 sm:py-18"><div className="rounded-[32px] border border-[var(--lx-surface)] bg-gradient-to-br from-white via-[var(--lx-surface)] to-[var(--lx-surface)] p-7 sm:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[var(--lx-primary)]">CURRENT DEVELOPMENT FOCUS</p><h2 className="mt-3 text-3xl font-black tracking-[-.05em]">Documentation that evolves with the product.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[var(--lx-muted)]">Recent work formalizes the Learn/Teach boundary, Lurexa Teach’s trusted evidence and credential pipeline, and Core/Mind responsibilities. This portal now has a structure capable of surfacing those decisions rather than hiding them in a generic homepage.</p></div><div className="grid gap-3 sm:grid-cols-2"><Link href="/architecture" className="rounded-2xl border border-[var(--lx-surface)] bg-white p-5"><b className="text-sm">Teach MVP architecture</b><p className="mt-2 text-xs leading-5 text-[var(--lx-muted)]">Trust, evidence, assessment, credentials, Mind.</p></Link><Link href="/product" className="rounded-2xl border border-[var(--lx-surface)] bg-white p-5"><b className="text-sm">Learn ↔ Teach boundary</b><p className="mt-2 text-xs leading-5 text-[var(--lx-muted)]">Operational learning vs educator development.</p></Link></div></div></div></section>
  </main></DocsShell>;
}
