import { MasterMark } from "@lurexa/ui/MasterMark";
import { ProductMark } from "@lurexa/ui/ProductMark";

const learners = [
  ["José Luis", "Pronunciation: /θ/", "Review"],
  ["Ana Rodríguez", "Low activity this week", "Review"],
  ["Michael Peña", "Ready for B1 challenge", "Ready"],
];
const navItems = ["Overview", "My classes", "Learner insights", "Assignments", "Resources"];
const ecosystemUrl = process.env.NEXT_PUBLIC_LUREXA_ECOSYSTEM_URL ?? "https://lurexa.com";
const teachUrl = process.env.NEXT_PUBLIC_LUREXA_TEACH_URL ?? `${ecosystemUrl}#products`;

export default function TeacherPortalHome() {
  return <main className="min-h-screen bg-[#f6f8ff] text-[#071d67]"><div className="grid min-h-screen md:grid-cols-[272px_1fr]">
    <aside className="hidden bg-[#071d67] p-7 text-indigo-100 md:flex md:flex-col">
      <div>
        <ProductMark product="learn" inverse />
        <p className="mt-3 text-xs font-bold leading-5 text-indigo-200">Teacher dashboard</p>
        <p className="mt-1 max-w-[190px] text-xs leading-5 text-indigo-300">Manage learning, classes, assignments, and learner progress inside Lurexa Learn.</p>
      </div>
      <p className="mt-10 text-[10px] font-extrabold tracking-[.2em] text-[#7ee9ed]">LEARN · TEACHER WORKSPACE</p>
      <nav className="mt-4 space-y-1.5" aria-label="Lurexa Learn teacher navigation">{navItems.map((item,index)=><button key={item} type="button" aria-current={index===0?"page":undefined} className={`min-h-11 w-full rounded-xl px-4 py-3 text-left text-sm font-bold transition motion-reduce:transition-none ${index===0?"bg-white text-[#071d67] shadow-lg shadow-black/10":"text-indigo-200 hover:bg-white/10 hover:text-white"}`}>{item}</button>)}</nav>
      <div className="mt-auto space-y-5 pt-8">
        <a href={teachUrl} className="block rounded-2xl border border-white/10 bg-white/[.06] p-4 transition hover:border-[#7ee9ed]/40 hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#7ee9ed] motion-reduce:transition-none" aria-label="Explore Lurexa Teach, professional growth and community for teachers">
          <ProductMark product="teach" inverse />
          <p className="mt-3 text-xs font-bold text-white">Professional growth & community</p>
          <p className="mt-1 text-xs leading-5 text-indigo-300">A separate Lurexa product for teachers to develop their skills, advance their level, collaborate, and learn with other educators.</p>
          <span className="mt-3 inline-flex min-h-9 items-center text-[11px] font-extrabold text-[#7ee9ed]">Explore Lurexa Teach <span className="ml-1" aria-hidden="true">↗</span></span>
        </a>
        <div className="border-t border-white/10 pt-5 text-sm"><b className="text-white">Damian Castro</b><p className="mt-1 text-indigo-300">English educator</p></div>
      </div>
    </aside>
    <section className="min-w-0 p-5 sm:p-8 md:p-12"><header className="flex flex-wrap items-start justify-between gap-5"><div className="flex min-w-0 items-start gap-4"><div className="rounded-2xl border border-[#dfe7fb] bg-white p-3 shadow-[0_10px_24px_rgba(32,52,128,.08)] md:hidden"><ProductMark product="learn" compact /></div><div><p className="text-[10px] font-extrabold tracking-[.2em] text-[#592bd6]">LUREXA LEARN · TEACHER DASHBOARD</p><h1 className="mt-3 text-3xl font-extrabold tracking-[-.06em] sm:text-5xl">Good morning, Damian.</h1><p className="mt-3 max-w-xl text-sm leading-6 text-[#6677a5]">Manage your classes and act on the clearest opportunities to support your learners.</p></div></div><div className="flex items-center gap-2"><a href={ecosystemUrl} aria-label="Go to the Lurexa ecosystem home" title="Lurexa ecosystem" className="grid min-h-11 min-w-11 place-items-center rounded-xl border border-[#d7e0f6] bg-white px-2 shadow-sm transition hover:-translate-y-0.5 hover:border-[#aebfec] hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1d5add] focus-visible:ring-offset-2 motion-reduce:transform-none motion-reduce:transition-none"><MasterMark compact /></a><button type="button" className="min-h-11 rounded-xl bg-gradient-to-br from-[#592bd6] to-[#1d5add] px-5 py-3 text-sm font-extrabold text-white shadow-[0_14px_26px_rgba(50,63,184,.25)] transition hover:-translate-y-0.5 motion-reduce:transform-none motion-reduce:transition-none">Create activity <span className="ml-1" aria-hidden="true">↗</span></button></div></header>
      <nav className="mt-6 flex gap-2 overflow-x-auto pb-2 md:hidden" aria-label="Lurexa Learn teacher mobile navigation">{navItems.map((item,index)=><button key={item} type="button" aria-current={index===0?"page":undefined} className={`min-h-11 shrink-0 rounded-full border px-4 text-sm font-extrabold ${index===0?"border-[#592bd6] bg-[#592bd6] text-white":"border-[#d7e0f6] bg-white text-[#3450a8]"}`}>{item}</button>)}</nav>
      <div className="mt-10 grid gap-4 md:grid-cols-3">{[["ACTIVE LEARNERS","126","+8 this week"],["CLASS MOMENTUM","82%","↑ 12% from last week"],["NEEDS REVIEW","9","3 priority learners"]].map(([label,value,detail],index)=><article key={label} className={`rounded-[22px] border p-6 shadow-[0_12px_30px_rgba(32,52,128,.07)] ${index===1?"border-[#c8c2ff] bg-[#eeeaff]":"border-[#dfe7fb] bg-white"}`}><p className="text-[10px] font-extrabold tracking-[.16em] text-[#6677a5]">{label}</p><b className="mt-3 block text-4xl tracking-[-.06em]">{value}</b><p className="mt-3 text-sm font-bold text-[#167c76]">{detail}</p></article>)}</div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><article className="rounded-[24px] border border-[#dfe7fb] bg-white p-7 shadow-[0_12px_30px_rgba(32,52,128,.07)]"><p className="text-[10px] font-extrabold tracking-[.18em] text-[#592bd6]">CLASS MOMENTUM</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-.04em]">Speaking confidence</h2><div aria-label="Speaking confidence trend" className="my-10 overflow-hidden text-4xl tracking-[.18em] text-[#592bd6] sm:text-5xl">▁▂▃▄▅▅▆▇</div><p className="text-sm font-semibold text-[#6677a5]"><span className="text-[#12aab0]" aria-hidden="true">●</span> Speaking confidence <span className="float-right">Target 80%</span></p></article><article className="relative overflow-hidden rounded-[24px] bg-gradient-to-br from-[#071d67] via-[#173a9d] to-[#2458c9] p-7 text-white shadow-[0_18px_36px_rgba(32,52,128,.2)]"><div className="absolute -right-10 -top-10 h-36 w-36 rounded-full bg-[#12cdd4]/25 blur-2xl"/><p className="relative text-[10px] font-extrabold tracking-[.18em] text-[#7ee9ed]">LUREXA MIND · AI INSIGHT</p><h2 className="relative mt-3 text-xl font-extrabold tracking-[-.04em]">Your class is ready for a live speaking challenge.</h2><p className="relative mt-4 text-sm leading-6 text-indigo-100">Confidence is rising across A2. Focus feedback this week on /θ/ and connected speech.</p><button type="button" className="relative mt-7 min-h-11 rounded-xl bg-white/12 px-4 py-2.5 text-sm font-extrabold text-[#9df4ee] transition hover:bg-white hover:text-[#173a9d] motion-reduce:transition-none">View recommendation →</button></article></div>
      <article className="mt-5 rounded-[24px] border border-[#dfe7fb] bg-white p-7 shadow-[0_12px_30px_rgba(32,52,128,.07)]"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[#592bd6]">LEARNERS TO SUPPORT</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-.04em]">Timely intervention</h2></div><button type="button" className="min-h-11 rounded-lg px-2 text-sm font-extrabold text-[#1d5add] hover:bg-[#eef3ff]">View all learners →</button></div>{learners.map(([name,detail,status])=><div key={name} className="mt-5 flex flex-col items-start justify-between gap-4 border-t border-[#edf1fb] pt-5 sm:flex-row sm:items-center"><div><b className="text-[#10245f]">{name}</b><p className="mt-1 text-sm text-[#6677a5]">{detail}</p></div><button type="button" className={`min-h-11 w-full rounded-lg px-3 py-2 text-sm font-extrabold sm:w-auto ${status==="Ready"?"bg-[#e4f8f2] text-[#137867]":"bg-[#fff3dc] text-[#a66013]"}`}>{status} →</button></div>)}</article>
      <a href={teachUrl} className="mt-6 flex flex-col gap-4 rounded-[24px] border border-[#dfe7fb] bg-white p-6 shadow-[0_12px_30px_rgba(32,52,128,.06)] transition hover:-translate-y-0.5 hover:border-[#c9d7f7] hover:shadow-[0_16px_34px_rgba(32,52,128,.1)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#1d5add] focus-visible:ring-offset-2 motion-reduce:transform-none motion-reduce:transition-none md:hidden"><ProductMark product="teach"/><div><p className="text-sm font-extrabold text-[#10245f]">Grow beyond the classroom dashboard.</p><p className="mt-1 text-sm leading-6 text-[#6677a5]">Lurexa Teach is the separate professional-development and teacher-community product.</p></div><span className="text-sm font-extrabold text-[#1d5add]">Explore Teach →</span></a>
    </section>
  </div></main>;
}
