const learners = [
  ["José Luis", "Pronunciation: /θ/", "Review"],
  ["Ana Rodríguez", "Low activity this week", "Review"],
  ["Michael Peña", "Ready for B1 challenge", "Ready"],
];
const ecosystemUrl = process.env.NEXT_PUBLIC_LUREXA_ECOSYSTEM_URL ?? "https://lurexa.com";

export default function TeacherPortalHome() {
  return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="grid min-h-screen md:grid-cols-[256px_1fr]">
    <aside className="hidden bg-slate-950 p-7 text-indigo-100 md:flex md:flex-col"><a href={ecosystemUrl} className="text-xl font-bold text-white">✦ Lurexa<span className="text-indigo-300"> Teach</span></a><p className="mt-10 text-xs font-bold tracking-widest text-indigo-300">TEACHER SPACE</p>{["Overview","My classes","Learner insights","Assignments","Resources"].map((item,index)=><button key={item} type="button" className={`mt-2 rounded-lg px-3 py-2 text-left text-sm transition ${index===0?"bg-indigo-500 text-white":"text-indigo-200 hover:bg-white/10"}`}>{item}</button>)}<div className="mt-auto border-t border-white/10 pt-5 text-sm"><b>Damian Castro</b><p className="text-indigo-300">English educator</p><a href={ecosystemUrl} className="mt-4 inline-block text-xs font-bold text-teal-300 hover:text-white">Back to ecosystem →</a></div></aside>
    <section className="p-5 sm:p-8 md:p-12"><header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold tracking-widest text-slate-500">TEACHER DASHBOARD</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">Good morning, Damian.</h1><p className="mt-2 text-sm text-slate-500">Your next best moments to support learners are ready.</p></div><div className="flex gap-2"><a href={ecosystemUrl} className="rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-bold text-slate-700 hover:border-indigo-200 hover:text-indigo-700 md:hidden">Ecosystem</a><button type="button" className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:bg-indigo-500">Create activity</button></div></header>
      <div className="mt-9 grid gap-4 md:grid-cols-3">{[["ACTIVE LEARNERS","126","+8 this week"],["CLASS MOMENTUM","82%","↑ 12% from last week"],["NEEDS REVIEW","9","3 priority learners"]].map(([label,value,detail])=><article key={label} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold tracking-wider text-slate-500">{label}</p><b className="mt-3 block text-4xl">{value}</b><p className="mt-2 text-sm text-teal-600">{detail}</p></article>)}</div>
      <div className="mt-5 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><article className="rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold tracking-wider text-indigo-600">CLASS MOMENTUM</p><h2 className="mt-2 text-xl font-bold">Speaking confidence</h2><div aria-label="Speaking confidence trend" className="my-10 text-4xl tracking-[.18em] text-indigo-500 sm:text-5xl">▁▂▃▄▅▅▆▇</div><p className="text-sm text-slate-500">● Speaking confidence <span className="float-right">Target 80%</span></p></article><article className="rounded-2xl bg-slate-950 p-7 text-white"><p className="text-xs font-bold tracking-wider text-teal-300">AI INSIGHT</p><h2 className="mt-3 text-xl font-bold">Your class is ready for a live speaking challenge.</h2><p className="mt-4 text-sm leading-6 text-slate-300">Confidence is rising across A2. Focus feedback this week on /θ/ and connected speech.</p><button type="button" className="mt-6 text-sm font-bold text-teal-300 hover:text-white">View recommendation →</button></article></div>
      <article className="mt-5 rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-100"><p className="text-xs font-bold tracking-wider text-indigo-600">LEARNERS TO SUPPORT</p><h2 className="mt-2 text-xl font-bold">Timely intervention</h2>{learners.map(([name,detail,status])=><div key={name} className="mt-4 flex items-center justify-between gap-4 border-t border-slate-100 pt-4"><div><b>{name}</b><p className="text-sm text-slate-500">{detail}</p></div><button type="button" className={status==="Ready"?"font-bold text-teal-600":"font-bold text-amber-600"}>{status} →</button></div>)}</article>
    </section>
  </div></main>;
}