#:schema node_modules/wrangler/config-schema.json
name = "lurexa-teach"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "enable_weak_ref", "allow_eval_during_startup"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "teach.lurexa.org"
custom_domain = true
