import type { TeachCourse, TeachCredentialDefinition } from "@lurexa/types";

const timestamp = "2026-08-20T00:00:00.000Z";

export const TEACH_MVP_COURSES: TeachCourse[] = [
  {
    id: "english-educators-b2-c1",
    title: "English for educators: B2 → C1",
    description: "Grow professional English through instruction, feedback, meetings, explanation, and academic discussion.",
    track: "english-proficiency",
    cefrTarget: "C1",
    competencyIds: ["professional-english", "academic-discussion", "feedback-language"],
    modules: [
      { id: "feedback-language", title: "Giving precise corrective feedback", order: 1, competencyIds: ["feedback-language"], evidenceRequired: true },
      { id: "instruction-language", title: "Explaining and checking understanding", order: 2, competencyIds: ["professional-english"], evidenceRequired: true },
      { id: "academic-discussion", title: "Professional and academic discussion", order: 3, competencyIds: ["academic-discussion"], evidenceRequired: true },
      { id: "c1-checkpoint", title: "C1 professional performance checkpoint", order: 4, competencyIds: ["professional-english", "academic-discussion"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "pronunciation-clearer-instruction",
    title: "Pronunciation for clearer instruction",
    description: "Develop intelligible professional speech and learn how to teach pronunciation without accent erasure.",
    track: "teaching-practice",
    competencyIds: ["pronunciation-pedagogy", "professional-english"],
    modules: [
      { id: "intelligibility", title: "Intelligibility before imitation", order: 1, competencyIds: ["pronunciation-pedagogy"] },
      { id: "transfer", title: "Spanish-to-English transfer patterns", order: 2, competencyIds: ["pronunciation-pedagogy"] },
      { id: "feedback", title: "Correct without breaking fluency", order: 3, competencyIds: ["pronunciation-pedagogy"], evidenceRequired: true },
      { id: "simulation", title: "Classroom feedback simulation", order: 4, competencyIds: ["professional-english", "pronunciation-pedagogy"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "teaching-speaking-confidence",
    title: "Teaching speaking with confidence",
    description: "Design speaking tasks that increase learner talk time, interaction quality, and useful feedback.",
    track: "teaching-practice",
    competencyIds: ["speaking-instruction", "task-design"],
    modules: [
      { id: "talk-time", title: "Increase meaningful student talk time", order: 1, competencyIds: ["speaking-instruction"] },
      { id: "scaffolding", title: "Scaffold interaction without scripting it", order: 2, competencyIds: ["task-design"] },
      { id: "feedback-loop", title: "Build a feedback loop", order: 3, competencyIds: ["speaking-instruction"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "assessment-supports-learning",
    title: "Assessment that supports learning",
    description: "Use formative evidence, transparent criteria, and feedback to improve learning while it is happening.",
    track: "assessment",
    competencyIds: ["assessment-for-learning", "rubric-design"],
    modules: [
      { id: "evidence", title: "Choose evidence that matters", order: 1, competencyIds: ["assessment-for-learning"] },
      { id: "criteria", title: "Make success criteria usable", order: 2, competencyIds: ["rubric-design"] },
      { id: "feedback-action", title: "Turn feedback into next action", order: 3, competencyIds: ["assessment-for-learning"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "ai-literacy-language-teachers",
    title: "AI literacy for language teachers",
    description: "Use AI responsibly for planning, practice, feedback, differentiation, and professional judgment.",
    track: "ai-digital",
    competencyIds: ["ai-literacy", "digital-pedagogy"],
    modules: [
      { id: "ai-judgment", title: "Know what AI should and should not decide", order: 1, competencyIds: ["ai-literacy"] },
      { id: "workflow", title: "Build a useful classroom AI workflow", order: 2, competencyIds: ["digital-pedagogy"], evidenceRequired: true },
      { id: "evaluation", title: "Evaluate AI output before learners see it", order: 3, competencyIds: ["ai-literacy"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "designing-asynchronous-learning",
    title: "Designing asynchronous learning",
    description: "Create coherent asynchronous sequences that keep learners active, supported, and accountable.",
    track: "course-design",
    competencyIds: ["asynchronous-design", "learning-sequencing"],
    modules: [
      { id: "sequence", title: "Sequence for cognitive and language load", order: 1, competencyIds: ["learning-sequencing"] },
      { id: "interaction", title: "Design meaningful asynchronous interaction", order: 2, competencyIds: ["asynchronous-design"] },
      { id: "redesign", title: "Redesign one real learning week", order: 3, competencyIds: ["asynchronous-design", "learning-sequencing"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "advanced-classroom-discourse-c1-c2",
    title: "Advanced classroom discourse & fluency (C1 → C2)",
    description: "Master spontaneous idiomatic communication, academic debating, and nuanced feedback phrasing for advanced English educators.",
    track: "english-proficiency",
    cefrTarget: "C2",
    competencyIds: ["professional-english", "academic-discussion", "spontaneous-fluency"],
    modules: [
      { id: "idiomatic-precision", title: "Idiomatic precision in teacher talk", order: 1, competencyIds: ["professional-english"] },
      { id: "academic-debating", title: "Facilitating advanced academic discussions", order: 2, competencyIds: ["academic-discussion"] },
      { id: "spontaneous-repair", title: "Real-time linguistic repair and recast modeling", order: 3, competencyIds: ["spontaneous-fluency"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "generative-ai-lesson-scaffolding",
    title: "Generative AI prompt engineering for lesson scaffolding",
    description: "Leverage LLMs and multimodal tools to generate leveled reading passages, differentiated drills, and diagnostic rubrics aligned with CEFR standards.",
    track: "ai-digital",
    competencyIds: ["ai-literacy", "digital-pedagogy", "prompt-engineering"],
    modules: [
      { id: "prompt-fundamentals", title: "System prompting for CEFR level calibration", order: 1, competencyIds: ["ai-literacy"] },
      { id: "differentiated-materials", title: "Generating multi-tier reading & speaking tasks", order: 2, competencyIds: ["digital-pedagogy"] },
      { id: "ai-bias-verification", title: "Pedagogical fact-checking and bias mitigation", order: 3, competencyIds: ["ai-literacy"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "competency-based-curriculum-architecture",
    title: "Competency-based curriculum & modular syllabus architecture",
    description: "Design modular, backward-designed learning units mapped to discrete communicative competencies and transparent performance evidence.",
    track: "course-design",
    competencyIds: ["course-design", "asynchronous-design", "competency-architecture"],
    modules: [
      { id: "backward-design", title: "Backward design from target communicative competencies", order: 1, competencyIds: ["course-design"] },
      { id: "modular-staging", title: "Structuring 4-week iterative practice cycles", order: 2, competencyIds: ["asynchronous-design"] },
      { id: "evidence-mapping", title: "Mapping portfolio tasks to certification milestones", order: 3, competencyIds: ["competency-architecture"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "teaching-specialized-industry-english",
    title: "Teaching specialized industry English (BPO, Tourism & Tech)",
    description: "Master pedagogy and curriculum adaptation for specialized workplace domains including BPO customer service, Caribbean hospitality, and software engineering teams.",
    track: "teaching-practice",
    competencyIds: ["industry-pedagogy", "curriculum-adaptation", "task-based-learning"],
    modules: [
      { id: "bpo-pedagogy", title: "BPO English: Scripts, tone, and verification", order: 1, competencyIds: ["industry-pedagogy"] },
      { id: "tourism-pedagogy", title: "Tourism & Hospitality: Authentic situational dialogues", order: 2, competencyIds: ["industry-pedagogy"] },
      { id: "tech-pedagogy", title: "Software Engineering: Agile ceremonies & technical discourse", order: 3, competencyIds: ["industry-pedagogy"] },
      { id: "industry-capstone", title: "Designing an industry-specific lesson unit", order: 4, competencyIds: ["industry-pedagogy", "curriculum-adaptation"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "contrastive-phonology-multi-l1-pedagogy",
    title: "Contrastive phonology & multi-L1 pronunciation pedagogy",
    description: "Diagnose and remediate Spanish-to-English phonological transfer across Dominican, Puerto Rican, Mexican, and Colombian learner profiles with an intelligibility-first methodology.",
    track: "teaching-practice",
    competencyIds: ["contrastive-phonology", "pronunciation-pedagogy", "l1-transfer-remediation"],
    modules: [
      { id: "contrastive-foundations", title: "Principles of contrastive phonological analysis", order: 1, competencyIds: ["contrastive-phonology"] },
      { id: "caribbean-dialects", title: "Dominican & Puerto Rican transfer: Coda /s/, lateralization & tap neutralization", order: 2, competencyIds: ["contrastive-phonology"] },
      { id: "continental-dialects", title: "Mexican & Colombian transfer: Consonant retention, /v/ vs /b/, and vowel reduction", order: 3, competencyIds: ["contrastive-phonology"] },
      { id: "remediation-design", title: "Formulating targeted minimal-pair and articulatory drills", order: 4, competencyIds: ["contrastive-phonology", "l1-transfer-remediation"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: "formative-assessment-rubrics-speaking",
    title: "Formative assessment & speaking rubrics design",
    description: "Design transparent, CEFR-calibrated speaking rubrics and diagnostic frameworks for task-based and role-play evaluation.",
    track: "assessment",
    competencyIds: ["assessment-for-learning", "rubric-design", "speaking-evaluation"],
    modules: [
      { id: "rubric-calibration", title: "CEFR-aligned diagnostic descriptors", order: 1, competencyIds: ["rubric-design"] },
      { id: "roleplay-evaluation", title: "Evaluating live spoken interaction and repair strategies", order: 2, competencyIds: ["speaking-evaluation"] },
      { id: "formative-feedback", title: "Actionable feedback delivery that drives immediate improvement", order: 3, competencyIds: ["assessment-for-learning"], evidenceRequired: true },
    ],
    published: true,
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];

export const TEACH_MVP_CREDENTIALS: TeachCredentialDefinition[] = [
  {
    id: "t1-the-first-coherent-lesson",
    name: "T1: The First Coherent Lesson",
    description: "Demonstrates evidence-backed capability in lesson staging, goal alignment, clear task instructions, and cohesive flow.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "t1-the-first-coherent-lesson" },
      { id: "evidence", type: "verified-evidence", competencyId: "lesson-planning", minimumCount: 1 },
    ],
  },
  {
    id: "t2-pronunciation-clearer-instruction",
    name: "T2: Pronunciation for Clearer Instruction",
    description: "Demonstrates phonetic modeling, intelligibility calibration, and constructive feedback for Dominican and ESL learners.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "pronunciation-clearer-instruction" },
      { id: "evidence", type: "verified-evidence", competencyId: "pronunciation-pedagogy", minimumCount: 1 },
    ],
  },
  {
    id: "t3-interactive-learning-delivery",
    name: "T3: Interactive Learning Delivery & Engagement",
    description: "Demonstrates active elicitation, student talk-time optimization, and immediate communicative feedback loops.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "teaching-speaking-confidence" },
      { id: "evidence", type: "verified-evidence", competencyId: "speaking-instruction", minimumCount: 1 },
    ],
  },
  {
    id: "t4-cefr-adaptation-and-assessment",
    name: "T4: CEFR Adaptation & Formative Assessment",
    description: "Demonstrates mastery of rubric design, diagnostic placement analysis, and individualized adaptive remediation.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "assessment-supports-learning" },
      { id: "evidence", type: "verified-evidence", competencyId: "assessment-for-learning", minimumCount: 1 },
    ],
  },
  {
    id: "t5-pedagogical-leadership-mastery",
    name: "T5: Pedagogical Leadership & Mastery",
    description: "Demonstrates curriculum leadership, educator mentorship, advanced C1/C2 discourse modeling, and AI-assisted workflow governance.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "ai-literacy-language-teachers" },
      { id: "cefr", type: "cefr-level", cefrLevel: "C1" },
      { id: "evidence", type: "verified-evidence", competencyId: "ai-literacy", minimumCount: 1 },
    ],
  },
  {
    id: "credential-specialized-industry-instructor",
    name: "Specialized Industry English Instructor",
    description: "Demonstrates pedagogical mastery in delivering targeted, career-accelerating English training for BPO, Tourism, and Software Engineering professionals.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "teaching-specialized-industry-english" },
      { id: "evidence", type: "verified-evidence", competencyId: "industry-pedagogy", minimumCount: 1 },
    ],
  },
  {
    id: "credential-contrastive-phonology-specialist",
    name: "Contrastive Phonology & Pronunciation Specialist",
    description: "Demonstrates mastery of cross-dialect Spanish-to-English contrastive phonology and precision articulatory remediation.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "contrastive-phonology-multi-l1-pedagogy" },
      { id: "evidence", type: "verified-evidence", competencyId: "contrastive-phonology", minimumCount: 1 },
    ],
  },
  {
    id: "speaking-instruction-foundations",
    name: "Speaking Instruction Foundations",
    description: "Demonstrates evidence-backed capability in designing and facilitating speaking development.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "teaching-speaking-confidence" },
      { id: "evidence", type: "verified-evidence", competencyId: "speaking-instruction", minimumCount: 1 },
    ],
  },
  {
    id: "ai-informed-teaching-essentials",
    name: "AI-Informed Teaching Essentials",
    description: "Demonstrates responsible, evidence-based use of AI in teaching workflows.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "ai-literacy-language-teachers" },
      { id: "evidence", type: "verified-evidence", competencyId: "ai-literacy", minimumCount: 1 },
    ],
  },
  {
    id: "c1-english-for-educators",
    name: "C1 English for Educators",
    description: "Recognizes demonstrated C1 professional communication for educator contexts.",
    active: true,
    requirements: [
      { id: "course", type: "course-completion", courseId: "english-educators-b2-c1" },
      { id: "cefr", type: "cefr-level", cefrLevel: "C1" },
    ],
  },
];
