import { ProductMark } from "@lurexa/ui/ProductMark";
import { TeachShell } from "./components/TeachShell";

const pillars = [
  ["Language growth", "Strengthen your English from your current CEFR level with a path built for educators.", "A2 → C2"],
  ["Teaching practice", "Develop classroom skills through evidence-informed courses, demonstrations, and practical challenges.", "Practice"],
  ["Professional evidence", "Build a verified record of completed learning, projects, badges, and credentials.", "Credentials"],
  ["Teacher community", "Exchange ideas, resources, feedback, and support with educators who are growing too.", "Community"],
];

export default function TeachHome() {
  return <TeachShell active="Home"><main>
    <section className="relative overflow-hidden bg-gradient-to-br from-[var(--color-brand-navy)] via-[#172f88] to-[#4825a8] text-white"><div className="absolute -right-28 -top-28 h-[420px] w-[420px] rounded-full bg-[var(--lx-accent)]/15 blur-3xl"/><div className="mx-auto grid max-w-[1440px] gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1.05fr_.95fr] lg:py-28"><div className="relative"><p className="text-[11px] font-extrabold tracking-[.2em] text-[var(--lx-accent)]">PROFESSIONAL LEARNING FOR EDUCATORS</p><h1 className="mt-5 max-w-3xl text-5xl font-black leading-[.94] tracking-[-.065em] sm:text-7xl">Become the teacher your learners need next.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-indigo-100">Lurexa Teach connects English growth, teaching knowledge, real classroom practice, professional credentials, and a community of educators in one evolving professional profile.</p><div className="mt-9 flex flex-wrap gap-3"><a href="/dashboard" className="inline-flex min-h-12 items-center rounded-xl bg-white px-6 text-sm font-extrabold text-[#30218e] shadow-xl">Start your growth path →</a><a href="/courses" className="inline-flex min-h-12 items-center rounded-xl border border-white/20 bg-white/10 px-6 text-sm font-extrabold text-white">Explore learning</a></div><p className="mt-5 text-xs font-bold text-indigo-200">One educator profile. Language + pedagogy + evidence + community.</p></div><div className="relative grid place-items-center"><div className="w-full max-w-[520px] rounded-[34px] border border-white/15 bg-white/10 p-5 shadow-2xl backdrop-blur"><div className="rounded-[26px] bg-white p-6 text-[var(--color-brand-navy)]"><ProductMark product="teach"/><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#f2edff] p-5"><p className="text-[10px] font-extrabold tracking-[.15em] text-[var(--lx-primary)]">ENGLISH</p><b className="mt-2 block text-3xl">B2</b><p className="mt-1 text-xs text-[var(--lx-muted)]">Working toward C1</p></div><div className="rounded-2xl bg-[#e9fbf9] p-5"><p className="text-[10px] font-extrabold tracking-[.15em] text-[#137d7f]">PRACTICE</p><b className="mt-2 block text-3xl">74%</b><p className="mt-1 text-xs text-[var(--lx-muted)]">Evidence portfolio</p></div></div><div className="mt-3 rounded-2xl border border-[#e1e7f8] p-5"><p className="text-xs font-extrabold text-[var(--lx-primary)]">NEXT BEST STEP</p><b className="mt-2 block text-lg">Giving feedback that improves speaking</b><div className="mt-4 h-2 overflow-hidden rounded-full bg-[#edf1fb]"><div className="h-full w-[68%] rounded-full bg-gradient-to-r from-[var(--lx-primary)] to-[var(--lx-accent)]"/></div></div></div></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8"><p className="text-[11px] font-extrabold tracking-[.18em] text-[var(--lx-primary)]">ONE PROFESSIONAL JOURNEY</p><div className="mt-4 grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><h2 className="text-4xl font-black tracking-[-.055em] sm:text-5xl">Grow what you know, what you can do, and who you can learn with.</h2><p className="max-w-xl text-base leading-7 text-[var(--lx-muted)]">Teach is designed around durable professional capability—not content consumption. Every course should connect to practice, evidence, reflection, and the educator profile.</p></div><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{pillars.map(([title,copy,tag],i)=><article key={title} className="rounded-[26px] border border-[var(--lx-surface)] bg-white p-6 shadow-[0_12px_30px_rgba(32,52,128,.06)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-[#eee9ff] to-[#e6fbfa] text-sm font-black text-[var(--lx-primary)]">0{i+1}</span><p className="mt-6 text-[10px] font-extrabold tracking-[.15em] text-[#7280a6]">{tag}</p><h3 className="mt-2 text-xl font-black tracking-[-.035em]">{title}</h3><p className="mt-3 text-sm leading-6 text-[var(--lx-muted)]">{copy}</p></article>)}</div></section>
    <section className="mx-auto max-w-[1380px] rounded-[36px] bg-[#fffaf2] px-6 py-16 sm:px-10 lg:px-14"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-[11px] font-extrabold tracking-[.18em] text-[#a05e20]">COMMUNITY IS PART OF THE LEARNING</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-5xl">Teachers improve faster when professional growth stops being solitary.</h2><p className="mt-5 max-w-2xl text-base leading-7 text-[#76664e]">Join topic circles, ask for feedback, share classroom resources, find study partners, and participate in educator challenges.</p></div><a href="/community" className="inline-flex min-h-12 items-center rounded-xl bg-[var(--color-brand-navy)] px-6 text-sm font-extrabold text-white">Enter the community →</a></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8"><div className="rounded-[34px] bg-gradient-to-r from-[var(--lx-primary)] to-[var(--lx-secondary)] p-8 text-white sm:p-12"><p className="text-[11px] font-extrabold tracking-[.18em] text-[#9af4ef]">YOUR NEXT PROFESSIONAL CHAPTER</p><h2 className="mt-4 max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-5xl">Build a professional record that grows with you.</h2><p className="mt-5 max-w-2xl leading-7 text-indigo-100">Your Lurexa Teach profile can become the evidence layer for learning, credentials, strengths, goals, and contributions across your teaching career.</p><a href="/growth" className="mt-7 inline-flex min-h-12 items-center rounded-xl bg-white px-6 text-sm font-extrabold text-[#4b2aaf]">View the growth model →</a></div></section>
  </main></TeachShell>;
}
