import { TeachShell } from "../components/TeachShell";
const courses=[
["English for educators: B2 → C1","Language growth","12 weeks","Your current path"],
["Pronunciation for clearer instruction","Language + practice","4 weeks","68% complete"],
["Teaching speaking with confidence","Pedagogy","5 weeks","Recommended"],
["Assessment that supports learning","Assessment","4 weeks","Recommended"],
["AI literacy for language teachers","Digital teaching","3 weeks","New"],
["Designing asynchronous learning","Course design","5 weeks","Popular"],
];
export default function CoursesPage(){return <TeachShell active="Learn"><main className="mx-auto max-w-[1440px] px-5 py-10 sm:px-8"><section className="grid gap-7 lg:grid-cols-[1fr_.8fr] lg:items-end"><div><p className="text-[11px] font-extrabold tracking-[.18em] text-[#6b2bd9]">PROFESSIONAL LEARNING</p><h1 className="mt-3 max-w-3xl text-4xl font-black tracking-[-.055em] sm:text-6xl">Courses that end in capability, not just completion.</h1></div><p className="max-w-xl text-base leading-7 text-[#6677a5]">Every learning path connects knowledge to practice, reflection, evidence, and the educator profile. Language development can be combined with pedagogy instead of treated as a separate track.</p></section><section className="mt-9 flex flex-wrap gap-2">{["For you","English growth","Teaching practice","Assessment","Technology","Course design"].map((x,i)=><button key={x} className={`min-h-11 rounded-full border px-4 text-sm font-extrabold ${i===0?"border-[#6b2bd9] bg-[#6b2bd9] text-white":"border-[#d7e0f6] bg-white text-[#536ba5]"}`}>{x}</button>)}</section><section className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{courses.map(([title,area,time,status],i)=><article key={title} className="group flex min-h-[290px] flex-col rounded-[26px] border border-[#dfe6f8] bg-white p-6 shadow-[0_12px_30px_rgba(32,52,128,.06)] transition hover:-translate-y-1 hover:shadow-[0_20px_38px_rgba(32,52,128,.1)]"><div className={`h-2 w-16 rounded-full ${i%3===0?"bg-[#6b2bd9]":i%3===1?"bg-[#315fd7]":"bg-[#12cdd4]"}`}/><p className="mt-6 text-[10px] font-extrabold uppercase tracking-[.15em] text-[#7180a8]">{area}</p><h2 className="mt-2 text-2xl font-black tracking-[-.04em]">{title}</h2><p className="mt-3 text-sm leading-6 text-[#6677a5]">Build useful professional knowledge through short explanations, models, practice tasks, peer reflection, and evidence.</p><div className="mt-auto flex items-end justify-between gap-3 pt-6"><div><b className="text-sm text-[#315fd7]">{status}</b><p className="mt-1 text-xs text-[#8994b4]">{time}</p></div><span className="grid h-11 w-11 place-items-center rounded-full bg-[#f0ecff] font-black text-[#6b2bd9]">→</span></div></article>)}</section><section className="mt-12 rounded-[30px] bg-[#071d67] p-7 text-white sm:p-10"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[#8df4ef]">PERSONALIZED PATHWAYS</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em]">Not sure what to study next?</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100">Lurexa Mind can combine your English level, teaching goals, practice evidence, and interests to recommend the next highest-value learning sequence.</p></div><a href="/growth" className="inline-flex min-h-12 items-center rounded-xl bg-white px-5 text-sm font-extrabold text-[#26358c]">View my growth map →</a></div></section></main></TeachShell>}
