import type { Metadata } from "next";
import Link from "next/link";
import { DocsShell } from "../components/DocsShell";
import { searchDocs } from "../../lib/docs-content";
import { Button } from "@lurexa/ui/button";
import { Input } from "@lurexa/ui/Input";

export const metadata: Metadata = { title: "Search | Lurexa Docs", description: "Search canonical Lurexa repository documentation." };

export default async function DocsSearchPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams;
  const query = q.trim();
  const results = query ? searchDocs(query) : [];
  return <DocsShell><main className="mx-auto max-w-[1180px] px-5 py-12 sm:px-8 sm:py-16">
    <section className="rounded-[32px] bg-gradient-to-br from-[var(--color-brand-navy)] via-[var(--lx-secondary)] to-[var(--lx-primary)] p-8 text-white sm:p-10"><p className="text-[10px] font-extrabold tracking-[.18em] text-[var(--lx-accent)]">CANONICAL FULL-TEXT SEARCH</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em] sm:text-5xl">Search Lurexa Docs</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-indigo-100">Results are generated from the actual Markdown files under <code className="rounded bg-white/10 px-1.5 py-1">Docs/</code>. No duplicate web copy is indexed.</p><form action="/search" className="mt-7 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="docs-search">Search documentation</label><Input id="docs-search" name="q" defaultValue={query} placeholder="Try: learner model, CEFR, accessibility, Teach…" className="min-h-12 flex-1 rounded-2xl border border-white/20 bg-white px-4 text-sm font-bold text-[var(--color-brand-navy)] outline-none placeholder:text-[var(--lx-muted)] focus:ring-4 focus:ring-[var(--lx-accent)]/25"/><Button className="min-h-12 rounded-2xl bg-[var(--lx-accent)] px-6 text-sm font-black text-[var(--color-brand-navy)]">Search</Button></form></section>

    {!query ? <section className="mt-8 rounded-[26px] border border-dashed border-[var(--lx-border)] bg-white p-8 text-center"><h2 className="text-xl font-black">Search the source of truth.</h2><p className="mt-2 text-sm leading-6 text-[var(--lx-muted)]">Titles, paths, and Markdown content are searchable across the canonical repository documentation.</p></section> : <section className="mt-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[var(--lx-primary)]">RESULTS</p><h2 className="mt-2 text-3xl font-black tracking-[-.045em]">{results.length} match{results.length===1?"":"es"} for “{query}”</h2></div><Link href="/" className="text-sm font-extrabold text-[var(--lx-secondary)]">Docs home →</Link></div>{results.length ? <div className="mt-5 space-y-3">{results.map((result)=><Link key={result.relativePath} href={result.href} className="block rounded-[22px] border border-[var(--lx-surface)] bg-white p-6 shadow-[0_10px_28px_rgba(32,52,128,.045)] transition hover:-translate-y-0.5 hover:border-[var(--lx-border)] hover:shadow-[0_16px_34px_rgba(32,52,128,.08)]"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[var(--lx-surface)] px-2.5 py-1 text-[10px] font-extrabold uppercase tracking-[.1em] text-[var(--lx-primary)]">{result.section}</span><code className="break-all text-[10px] font-bold text-[var(--lx-muted)]">{result.relativePath}</code></div><h3 className="mt-3 text-xl font-black tracking-[-.035em]">{result.title}</h3><p className="mt-2 text-sm leading-7 text-[var(--lx-muted)]">{result.matchExcerpt}</p><span className="mt-4 inline-flex text-sm font-extrabold text-[var(--lx-secondary)]">Read canonical document →</span></Link>)}</div> : <div className="mt-5 rounded-[24px] border border-dashed border-[var(--lx-border)] bg-white p-9 text-center"><b className="text-lg">No canonical document matched that query.</b><p className="mt-2 text-sm text-[var(--lx-muted)]">Try a broader term or search by product, architecture concept, competency, or file topic.</p></div>}</section>}
  </main></DocsShell>;
}
