import { ProductMark } from "@lurexa/ui/ProductMark";
import { TeachReviewServerService } from "@lurexa/backend/teach-review.server";

export default async function VerifyCredentialPage({ params }: { params: Promise<{ verificationCode: string }> }) {
  const { verificationCode } = await params;
  const credential = await TeachReviewServerService.getPublicCredential(verificationCode);

  return <main className="min-h-screen bg-[#f5f7ff] px-5 py-12 text-[#0b1f5f] sm:px-8"><div className="mx-auto max-w-3xl"><div className="mb-8 flex justify-center"><ProductMark product="teach" /></div>{!credential?<section className="rounded-[30px] border border-[#efc4ce] bg-white p-8 text-center shadow-[0_18px_50px_rgba(32,52,128,.08)]"><p className="text-[10px] font-extrabold tracking-[.18em] text-[#a82b47]">CREDENTIAL VERIFICATION</p><h1 className="mt-3 text-3xl font-black">Credential not found.</h1><p className="mt-3 text-sm leading-6 text-[#6677a5]">Check the verification code exactly as issued by Lurexa.</p></section>:<section className="overflow-hidden rounded-[34px] border border-[#dfe6f8] bg-white shadow-[0_22px_60px_rgba(32,52,128,.12)]"><div className="bg-gradient-to-br from-[#071d67] via-[#1f3d98] to-[#592bd6] p-8 text-white sm:p-10"><div className="flex items-start justify-between gap-5"><div><p className="text-[10px] font-extrabold tracking-[.18em] text-[#8df4ef]">VERIFIED LUREXA CREDENTIAL</p><h1 className="mt-3 text-4xl font-black tracking-[-.05em]">{credential.credentialName}</h1></div><span className={`rounded-full px-3 py-1.5 text-xs font-extrabold ${credential.status==="valid"?"bg-[#8df4ef] text-[#075b57]":"bg-[#ffe2e7] text-[#a82b47]"}`}>{credential.status.toUpperCase()}</span></div><p className="mt-5 max-w-2xl text-sm leading-7 text-indigo-100">{credential.credentialDescription}</p></div><div className="grid gap-5 p-8 sm:grid-cols-2 sm:p-10"><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[#7180a8]">EDUCATOR</p><b className="mt-2 block text-xl">{credential.educatorDisplayName}</b></div><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[#7180a8]">ISSUED BY</p><b className="mt-2 block text-xl">{credential.issuer}</b></div><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[#7180a8]">AWARDED</p><b className="mt-2 block text-lg">{new Date(credential.awardedAt).toLocaleDateString()}</b></div><div><p className="text-[10px] font-extrabold tracking-[.16em] text-[#7180a8]">VERIFICATION CODE</p><code className="mt-2 block rounded-xl bg-[#f4f6fc] px-3 py-2 text-sm font-bold text-[#315fd7]">{credential.verificationCode}</code></div></div><div className="border-t border-[#edf1fb] bg-[#fbfcff] px-8 py-5 text-sm leading-6 text-[#6677a5] sm:px-10">This public record confirms the credential award without exposing internal evidence, assessment notes, or private educator identifiers.</div></section>}</div></main>;
}
